### ISSUE TITLE
Add Docker files for gdelt-climaterisk repository

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/gdelt-climaterisk#3]
## Description

We need to add Docker files to our gdelt-climaterisk repository to containerize our application. This will ensure consistent development and deployment environments.

## Tasks

- [ ] Create a Dockerfile based on the following specifications:

  - Base image: ghcr.io/entelecheia/devcon:latest-cuda-12.1.0-ubuntu22.04
  - Set container username to 'dev' with UID 9001
  - Set timezone to Asia/Seoul
  - Install any required apt packages (none specified in config)
  - Set up workspace at /workspace
  - Set up CUDA device ID 1

- [ ] Create a docker-compose.yml file with the following services:

  1. workspace:
     - Build from Dockerfile
     - Set environment variables
     - Map ports:
       - 19871:8585 for Jupyter
       - 2341:22 for SSH
       - 18761:8080 for web service
     - Enable NVIDIA GPU
     - Set up volumes for persistent data

- [ ] Create a launch script (launch.sh) for running the container

- [ ] Update .gitignore to exclude any unnecessary Docker-related files

- [ ] Add Docker-related entries to the project's documentation

## Additional Information

- Project name: gdelt-climaterisk
- Docker image name: COP_DECODER/gdelt-climaterisk
- Docker registry: ghcr.io
- Docker username: entelecheia
- Jupyter token: (empty in config, consider setting a secure token)
